# https://github.com/jmeischner/alfred-bear/blob/e96c016165462e186f35e3e090dfdabfbae2587c/.github/workflows/publish.yml
name: Publish

on:
  release:
    # This specifies that the build will be triggered when we publish a release
    types: [published]

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # "ref" specifies the branch to check out.
          # "github.event.release.target_commitish" is a global variable and specifies the branch the release targeted
          ref: ${{ github.event.release.target_commitish }}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci --ignore-scripts

      # set up git since we will later push to the repo
      - run: git config --global user.name "GitHub Publish Action"
      - run: git config --global user.email ""

      # upgrade npm version in package.json to the tag used in the release.
      - run: npm version ${{ github.event.release.tag_name }}

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      # push the version changes to GitHub
      - run: git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GITHUB_TOKEN }}
